### ISSUE TITLE
Source maps not emitted by default

### ISSUE THREAD

**Issue by kfeinUI** [tradingview/webpack-uglify-parallel#3]
When relying on the default configuration for the sourceMaps option (true), the source maps are not emitted in the build when using this plugin.

As a workaround, explicitly setting the configuration to true does the job.

**Comment by w0rse** [comment]
Hello! It's already fixed by @trevdor in https://github.com/tradingview/webpack-uglify-parallel/pull/1. Just published updated version to npm.
