### ISSUE TITLE
Race issue: Hangs on `91% additional asset processing`

### ISSUE THREAD

**Issue by nojvek** [tradingview/webpack-uglify-parallel#6]
This is our config

```
const {NUM_UGLIFY_WORKERS } = process.env;

...
      webpackConfig.plugins = globalPlugins.concat([
        new UglifyJsParallelPlugin({
          workers: NUM_UGLIFY_WORKERS || 8,
          sourceMap: true,
        }),
      ]);
```

It doesn't happen everytime, but when it does, it hangs endlessly until killed.

**Comment by w0rse** [comment]
Turning source maps off will most likely solve the problem, but is not an optimal solution of course. I strongly encourage you to migrate to official uglify plugin, as it now supports parallelization too.

**Comment by nojvek** [comment]
Migrating to the official uglify plugin helped. Thanks
